import { Work_Sans, Inter } from "next/font/google";
import "./globals.css";


// const heebo = Heebo({ subsets: ['latin'], display: "swap", variable: '--font-Heebo', });


const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '500','600','700', '800', '900'],
  variable: '--font-work-sans',
  display: 'swap',
});
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500','600','700', '800', '900'],
  variable: '--font-inter',
  display: 'swap',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
